/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iu;

import controladores.ControladorCarteleraElectronica;
import interfaces.VistaCarteleraElectronica;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import logica.Cochera;
import logica.Parking;
import logica.Tarifario;

/**
 *
 * @author sofia
 */
public class DialogoCarteleraElectronica extends javax.swing.JFrame implements VistaCarteleraElectronica {

    private final Parking parking;
    private final ControladorCarteleraElectronica controlador;

    /**
     * Creates new form CarteleraElectronica
     */
    public DialogoCarteleraElectronica(Parking p) {
        this.parking = p;
        initComponents();
        controlador = new ControladorCarteleraElectronica(this, parking);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreParking = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblDisponibilidad = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCocheras = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTipoVehiculo = new javax.swing.JTable();
        btnCerrarCartelera = new javax.swing.JButton();
        txtNombreParking = new javax.swing.JTextField();
        txtTotalCocheras = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setText("Cartelera Electrónica - ");

        lblNombreParking.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblDisponibilidad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDisponibilidad.setText("Disponibilidad: ");

        tableCocheras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cocheras", "Disponibilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCocheras);

        tableTipoVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Motocicleta", null},
                {"Standard", null},
                {"Carga", null},
                {"Pasajeros", null}
            },
            new String [] {
                "Tipo de vehículo", "Precio"
            }
        ));
        jScrollPane3.setViewportView(tableTipoVehiculo);

        btnCerrarCartelera.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCerrarCartelera.setText("Cerrar");
        btnCerrarCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCarteleraActionPerformed(evt);
            }
        });

        txtNombreParking.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N

        txtTotalCocheras.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreParking)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreParking, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(56, 56, 56))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(lblDisponibilidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalCocheras, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCerrarCartelera)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(jLabel1)
                    .addComponent(lblNombreParking)
                    .addComponent(txtNombreParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisponibilidad)
                    .addComponent(txtTotalCocheras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnCerrarCartelera)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCarteleraActionPerformed
        // TODO add your handling code here:
        new DialogoTableroDeControl().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCerrarCarteleraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarCartelera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDisponibilidad;
    private javax.swing.JLabel lblNombreParking;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tableCocheras;
    private javax.swing.JTable tableTipoVehiculo;
    private javax.swing.JTextField txtNombreParking;
    private javax.swing.JTextField txtTotalCocheras;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarNombreParking(String nombre) {
        txtNombreParking.setText(nombre);
    }

    @Override
    public void cargarTablaTarifario(ArrayList<Tarifario> tarifarios) {
        DefaultTableModel model = (DefaultTableModel) tableTipoVehiculo.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de agregar nuevas filas

        for (Tarifario tarifario : tarifarios) {
            model.addRow(new Object[]{tarifario.getTipoVehiculo().getTipo(), tarifario.getValorHora()});
        }
    }

    @Override
    public void mostrarCantCocherasDisponibles(int cocheras) {
        txtTotalCocheras.setText(cocheras + "");
    }

    @Override
    public void actualizarTablaDisponibilidad(Map<String, Integer> disponibilidad) {
        DefaultTableModel model = (DefaultTableModel) tableCocheras.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de agregar nuevas filas

        for (Map.Entry<String, Integer> entry : disponibilidad.entrySet()) {
            model.addRow(new Object[]{entry.getKey(), entry.getValue()});
        }
    }

}
