/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iu;

import controladores.ControladorListaDePrecios;
import interfaces.VistaListaDePrecios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Parking;
import logica.Tarifario;

/**
 *
 * @author sofia
 */
public class DialogoListaDePrecios extends javax.swing.JFrame implements VistaListaDePrecios {

    private final Parking parking;
    private final ControladorListaDePrecios controlador;
    private Tarifario tarifarioSeleccionado;

    /**
     * Creates new form ListaDePrecios
     */
    public DialogoListaDePrecios(Parking p) {
        this.parking = p;
        initComponents();
        this.controlador = new ControladorListaDePrecios(this, parking);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNuevoValor = new javax.swing.JLabel();
        txtNuevoValor = new javax.swing.JTextField();
        btnCerrarListaPrecios = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtNombreParking = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Lista de precios - ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo Vehículo", "Precio/<UT>"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblNuevoValor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblNuevoValor.setText("Nuevo valor: ");

        txtNuevoValor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtNuevoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoValorActionPerformed(evt);
            }
        });

        btnCerrarListaPrecios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCerrarListaPrecios.setText("Cerrar");
        btnCerrarListaPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarListaPreciosActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtNombreParking.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreParking, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblNuevoValor)
                            .addGap(4, 4, 4)
                            .addComponent(txtNuevoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnCerrarListaPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoValor)
                    .addComponent(txtNuevoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCerrarListaPrecios))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNuevoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoValorActionPerformed

    private void btnCerrarListaPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarListaPreciosActionPerformed
        // TODO add your handling code here:
        new DialogoTableroDeControl().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCerrarListaPreciosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guardarPrecio();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            String tarifario = jTable1.getValueAt(selectedRow, 0).toString();
            //llamo al metodo dentro de el controlador tablero para q devuelva el parking
            Tarifario seleccionado = controlador.getTarifarioSeleccionado(tarifario);
            this.tarifarioSeleccionado = seleccionado;
        }
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarListaPrecios;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNuevoValor;
    private javax.swing.JTextField txtNombreParking;
    private javax.swing.JTextField txtNuevoValor;
    // End of variables declaration//GEN-END:variables

    private void guardarPrecio() {

        if (tarifarioSeleccionado != null) {

            double nuevoPrecio = Double.parseDouble(txtNuevoValor.getText());
            controlador.guardarCambioDePrecioUT(tarifarioSeleccionado, nuevoPrecio);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar algun tarifario para poder guardar el nuevo valor");

        }
        
        txtNuevoValor.setText("");
    }

    @Override
    public void mostrarNombreParking(String nombre) {
        txtNombreParking.setText(nombre);
    }

    @Override
    public void mostrarMensajeDeError(String message) {
        JOptionPane.showMessageDialog(rootPane, message);

    }

    @Override
    public void actualizarTablaTarifario(ArrayList<Tarifario> tarifarios) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de agregar nuevas filas

        for (Tarifario tarifario : tarifarios) {
            model.addRow(new Object[]{tarifario.getTipoVehiculo().getTipo(), tarifario.getValorHora()});
        }
    }
}
